# Generated by Django 3.2.21 on 2023-10-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='tag',
            new_name='tags',
        ),
    ]
