# Generated by Django 3.2.21 on 2023-10-02 14:11

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_tag_group_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='hex_color',
            field=models.CharField(default='#4d10bd', max_length=7, null=True, validators=[django.core.validators.RegexValidator(re.compile('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$'), 'Enter a valid color')]),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
