# Generated by Django 3.2.21 on 2023-10-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_hex_color'),
        ('post', '0002_auto_20231006_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='groups.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, choices=[('VG', 'Very Good'), ('GD', 'Good'), ('NL', 'Normal'), ('BD', 'Bad'), ('VB', 'Very Bad')], max_length=2, null=True),
        ),
    ]
